/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vue;

import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import modele.dao.DaoSalarie;
import modele.metier.Salarie;
import modele.metier.Service;
import modele.metier.Categorie;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import java.util.Date;
import javax.swing.SwingUtilities;


/**
 *
 * @author Stefen R
 */
public class JDialogModifier extends javax.swing.JDialog {

    private DefaultComboBoxModel modeleJComboLesCategories;
    private DefaultComboBoxModel modeleJComboLesServices;
    private List<Categorie> desCategories;
    private List<Service> desServices;

    
    /**
     * Creates new form JDialogConsulter
     */
    public JDialogModifier(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.desCategories = new ArrayList<>();
    }
    
    public JDialogModifier(JFrameListeSalaries aThis, boolean par, List<Service> desServices,List<Categorie> desCategories, Salarie salarie) {
        initComponents();
        this.setLocation(150, 150);
    
        jTextFieldCode.setText(salarie.getCode());
        jTextFieldNom.setText(salarie.getNom());
        jTextFieldPrenom.setText(salarie.getPrenom());


        jDateChooserNaiss.setDate(salarie.getDateNaiss());
        jDateChooserEmbauche.setDate(salarie.getDateEmbauche());
  
        jTextFieldFonction.setText(salarie.getFonction());
    
        double tauxHoraire = salarie.getTauxHoraire();
        jTextFieldHoraire.setText(Double.toString(tauxHoraire));
     
        jTextFieldSitua.setText(salarie.getSituationFamiliale());
        jTextFieldEnfants.setText(Integer.toString(salarie.getNbrEnfants()));

        modeleJComboLesCategories = new DefaultComboBoxModel();
        jComboBoxCate.setModel(modeleJComboLesCategories);


        modeleJComboLesServices = new DefaultComboBoxModel();
        jComboBoxService.setModel(modeleJComboLesServices);
    


        remplirJComBoxCate(desCategories);
        this.desCategories = desCategories; // Initialise la liste des catégories
        
        remplirJComBoxService(desServices);
        this.desServices = desServices; // Initialise la liste des cservices
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelInformations = new javax.swing.JLabel();
        jButtonRetour = new javax.swing.JButton();
        jLabelCode = new javax.swing.JLabel();
        jLabelNom = new javax.swing.JLabel();
        jLabelPrenom = new javax.swing.JLabel();
        jLabelNaiss = new javax.swing.JLabel();
        jLabelEmbauche = new javax.swing.JLabel();
        jLabelFonction = new javax.swing.JLabel();
        jLabelService = new javax.swing.JLabel();
        jLabelCate = new javax.swing.JLabel();
        jTextFieldCode = new javax.swing.JTextField();
        jTextFieldNom = new javax.swing.JTextField();
        jTextFieldPrenom = new javax.swing.JTextField();
        jTextFieldFonction = new javax.swing.JTextField();
        jButtonModifier = new javax.swing.JButton();
        jComboBoxCate = new javax.swing.JComboBox<>();
        jLabelHoraire = new javax.swing.JLabel();
        jLabelFamille = new javax.swing.JLabel();
        jLabelNbrenfants = new javax.swing.JLabel();
        jTextFieldSitua = new javax.swing.JTextField();
        jTextFieldHoraire = new javax.swing.JTextField();
        jTextFieldEnfants = new javax.swing.JTextField();
        jComboBoxService = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelInformations.setText("Modification du salarié !");
        jLabelInformations.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonRetour.setText("Retour");
        jButtonRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetourActionPerformed(evt);
            }
        });

        jLabelCode.setText("Code :");
        jLabelCode.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelNom.setText("Nom :");
        jLabelNom.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelPrenom.setText("Prenom :");
        jLabelPrenom.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelNaiss.setText("Date naissance :");
        jLabelNaiss.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelEmbauche.setText("Date embauche :");
        jLabelEmbauche.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelFonction.setText("Fonction :");
        jLabelFonction.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelService.setText("Service :");
        jLabelService.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelCate.setText("Categorie :");
        jLabelCate.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodeActionPerformed(evt);
            }
        });

        jButtonModifier.setText("Modifier");
        jButtonModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierActionPerformed(evt);
            }
        });

        jComboBoxCate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelHoraire.setText("Taux horaire :");
        jLabelHoraire.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelFamille.setText("Situation familiale :");
        jLabelFamille.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelNbrenfants.setText("Nbr enfants :");
        jLabelNbrenfants.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jComboBoxService.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabelInformations)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelHoraire)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNbrenfants)
                                .addGap(105, 105, 105)
                                .addComponent(jTextFieldEnfants, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelFamille)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldSitua, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelService)
                                    .addComponent(jLabelCate))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxCate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxService, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonRetour)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonModifier))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNom)
                                    .addComponent(jLabelCode))
                                .addGap(139, 139, 139)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                    .addComponent(jTextFieldCode)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelPrenom)
                                    .addComponent(jLabelNaiss)
                                    .addComponent(jLabelEmbauche)
                                    .addComponent(jLabelFonction))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldFonction, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                    .addComponent(jTextFieldPrenom)
                                    .addComponent(jTextFieldHoraire, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))))
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabelInformations)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCode)
                    .addComponent(jTextFieldCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNom)
                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrenom)
                    .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelNaiss)
                .addGap(18, 18, 18)
                .addComponent(jLabelEmbauche)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFonction)
                    .addComponent(jTextFieldFonction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHoraire)
                    .addComponent(jTextFieldHoraire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFamille)
                    .addComponent(jTextFieldSitua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNbrenfants)
                    .addComponent(jTextFieldEnfants, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jComboBoxCate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelService)
                            .addComponent(jComboBoxService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelCate)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRetour)
                    .addComponent(jButtonModifier))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetourActionPerformed
        // TODO add your handling code here:
        this.toBack();
        setVisible(false);
    }//GEN-LAST:event_jButtonRetourActionPerformed

    private void jTextFieldCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodeActionPerformed

    private void jButtonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierActionPerformed
    // TODO add your handling code here:

    String code = jTextFieldCode.getText();
    String nom = jTextFieldNom.getText();
    String prenom = jTextFieldPrenom.getText();

    Date utilDateNaiss = jDateChooserNaiss.getDate();
    java.sql.Date naiss = new java.sql.Date(utilDateNaiss.getTime());

    Date utilDateEmbauche = jDateChooserEmbauche.getDate();
    java.sql.Date embauche = new java.sql.Date(utilDateEmbauche.getTime());

    String fonction  = jTextFieldFonction.getText();

    String tauxHoraire = jTextFieldHoraire.getText();
    double horaire = Double.parseDouble(tauxHoraire);

    String famille = jTextFieldSitua.getText();

    String nbrEnfants = jTextFieldEnfants.getText();
    int enfants = Integer.parseInt(nbrEnfants);

    String designationService = (String) jComboBoxService.getSelectedItem();
    int service = getCodeService(designationService);

    String libelleCategorie = (String) jComboBoxCate.getSelectedItem();
    String  categorie = getNumCategorie(libelleCategorie);


    try {
        DaoSalarie.ModifierSalarie(code,nom,prenom, naiss, embauche, fonction, horaire, famille, enfants, categorie, service);

        // Récupérer la JFrame parente
        JFrameListeSalaries frame = (JFrameListeSalaries) SwingUtilities.getAncestorOfClass(JFrameListeSalaries.class, this);
        if (frame instanceof JFrameListeSalaries) {
            ((JFrameListeSalaries) frame).remplirJTableSalaries(DaoSalarie.getAll());
        }
        
        // Retourner à la JFrame principale
        setVisible(false);
        getParent().setVisible(true);
    } catch (SQLException | IOException ex) {
        Logger.getLogger(JDialogModifier.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    }//GEN-LAST:event_jButtonModifierActionPerformed

    
    public void remplirJComBoxCate(List<Categorie> desCategories) {
        modeleJComboLesCategories.removeAllElements(); // Efface d'abord tous les éléments de la combobox
        // Ajoute ensuite les libellés des catégories à la combobox
        for (Categorie uneCategorie : desCategories) {
            modeleJComboLesCategories.addElement(uneCategorie.getLibelle());
        }
    }
    
    public String getNumCategorie(String libelleCategorie) {
    // Parcourir la liste des catégories pour trouver celle correspondant au libellé
    for (Categorie uneCategorie : desCategories) {
        if (uneCategorie.getLibelle().equals(libelleCategorie)) {
            return uneCategorie.getCode();
        }
    }
        return null;   
}
    
    public void remplirJComBoxService(List<Service> desServices) {
        modeleJComboLesServices.removeAllElements(); // Efface d'abord tous les éléments de la combobox
        // Ajoute ensuite les libellés des catégories à la combobox
        for (Service unService : desServices) {
            modeleJComboLesServices.addElement(unService.getDesignation());
        }
    }
    
    public int getCodeService(String designationService) {
    // Parcourir la liste des catégories pour trouver celle correspondant au libellé
    for (Service unService : desServices) {
        if (unService.getDesignation().equals(designationService)) {
            return unService.getCode();
        }
    }
        return 0;   
}
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogModifier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogModifier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogModifier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogModifier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogModifier dialog = new JDialogModifier(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonModifier;
    private javax.swing.JButton jButtonRetour;
    private javax.swing.JComboBox<String> jComboBoxCate;
    private javax.swing.JComboBox<String> jComboBoxService;
    private javax.swing.JLabel jLabelCate;
    private javax.swing.JLabel jLabelCode;
    private javax.swing.JLabel jLabelEmbauche;
    private javax.swing.JLabel jLabelFamille;
    private javax.swing.JLabel jLabelFonction;
    private javax.swing.JLabel jLabelHoraire;
    private javax.swing.JLabel jLabelInformations;
    private javax.swing.JLabel jLabelNaiss;
    private javax.swing.JLabel jLabelNbrenfants;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelPrenom;
    private javax.swing.JLabel jLabelService;
    private javax.swing.JTextField jTextFieldCode;
    private javax.swing.JTextField jTextFieldEnfants;
    private javax.swing.JTextField jTextFieldFonction;
    private javax.swing.JTextField jTextFieldHoraire;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldPrenom;
    private javax.swing.JTextField jTextFieldSitua;
    // End of variables declaration//GEN-END:variables
}
